const { chromium } = require('@playwright/test');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:3100');
 await page.getByRole('heading',{name:'A good day to make chocolate.'}).waitFor();
 await page.screenshot({path:'screen-production.png',fullPage:true});
 await page.getByRole('button',{name:'Open CB-025',exact:true}).click();
 await page.getByRole('button',{name:'Record winnowing',exact:true}).click();
 for(const [name,value] of [['Nibs','72'],['Whole peeled beans','5'],['Husks','13.8'],['Unusable beans','1.1']]) await page.getByRole('spinbutton',{name,exact:true}).fill(value);
 await page.screenshot({path:'screen-record-stage.png',fullPage:true});
 await page.getByRole('button',{name:'Save stage',exact:true}).click();
 await page.getByRole('button',{name:'Record grinding',exact:true}).waitFor();
 await page.getByRole('button',{name:'All batches',exact:true}).click();
 await page.getByRole('button',{name:'Open CH-018',exact:true}).click();
 await page.getByRole('button',{name:'Record moulding',exact:true}).click();
 await page.getByRole('spinbutton',{name:'Finished chocolate',exact:true}).fill('94.8');
 await page.getByRole('spinbutton',{name:'Recoverable chocolate',exact:true}).fill('1.2');
 await page.getByRole('button',{name:'Save stage',exact:true}).click();
 await page.getByRole('button',{name:'Record packaging',exact:true}).click();
 await page.getByRole('spinbutton',{name:'Total units made'}).fill('1896');
 await page.getByRole('spinbutton',{name:'Rejected units'}).fill('14');
 await page.getByRole('button',{name:'Save packaging',exact:true}).click();
 await page.getByRole('button',{name:'Review & complete',exact:true}).click();
 await page.getByRole('button',{name:'Complete batch',exact:true}).click();
 await page.getByText('Completed',{exact:true}).waitFor();
 await page.getByRole('button',{name:'All batches',exact:true}).click();
 await page.getByRole('button',{name:'New batch',exact:true}).click();
 await page.getByRole('spinbutton',{name:'Starting weight'}).fill('50');
 await page.getByRole('button',{name:'Create batch',exact:true}).click();
 await page.getByRole('button',{name:'Record roasting',exact:true}).waitFor();
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'screen-mobile.png',fullPage:true});
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
 console.log(JSON.stringify({flows:'batch creation, winnowing, moulding, packaging and completion passed',errors,mobileOverflow:overflow}));
 await browser.close();if(errors.length||overflow)process.exit(1);
})().catch(e=>{console.error(e);process.exit(1)});
