const {chromium}=require('@playwright/test');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:3100');
const nav=async n=>page.locator('nav button').filter({hasText:n}).click();
await nav('Production');await page.getByRole('heading',{name:'From beans to finished chocolate.'}).waitFor();await page.screenshot({path:'screen-processes.png',fullPage:true});
for(const name of ['Receiving','Roasting','Winnowing','Grinding','Pressing','Mixing','Refining','Conching','Tempering','Moulding','Packaging','Completion']){await page.locator('.process-card').filter({has:page.getByRole('heading',{name,exact:true})}).click();await page.getByRole('heading',{name,exact:true}).waitFor();await page.getByRole('button',{name:'Production processes',exact:true}).click();}
await page.locator('.process-card').filter({has:page.getByRole('heading',{name:'Pressing',exact:true})}).click();await page.getByRole('button',{name:/CB-025 · Cocoa beans/}).click();await page.getByRole('spinbutton',{name:'Cocoa butter',exact:true}).fill('21.4');await page.getByRole('spinbutton',{name:'Cocoa cake',exact:true}).fill('27.8');await page.getByRole('button',{name:'Save measurements'}).click();await page.getByRole('heading',{name:'Where does each output go?'}).waitFor();await page.getByRole('button',{name:'Save destinations'}).click();
await nav('Inventory');await page.getByRole('button',{name:'Open NIB-025',exact:true}).click();await page.getByRole('button',{name:'Trace this material'}).click();await page.getByRole('heading',{name:'Follow nibs'}).waitFor();
await nav('Inventory');await page.getByRole('button',{name:'Receive material'}).click();await page.getByRole('spinbutton',{name:'Measured weight (kg)'}).fill('50');await page.getByRole('button',{name:'Save receipt'}).click();await page.getByRole('button',{name:'Use or transfer'}).waitFor();
await nav('Formulations');await page.getByRole('button',{name:/70% Dark chocolate/}).click();await page.getByRole('button',{name:'Use this formulation'}).click();await page.getByRole('heading',{name:'What did you actually use?'}).waitFor();await page.getByRole('button',{name:'Start chocolate batch'}).click();await page.getByRole('heading',{name:'70% Dark chocolate'}).waitFor();
await nav('Reports');for(const n of ['Waste & variance','Finished output','Formulation comparison','Batch history','Stage performance']){await page.getByRole('button',{name:n,exact:true}).click();await page.getByRole('heading',{name:n,exact:true}).waitFor();}
await nav('Configuration');for(const n of ['Routes','Output categories','Products & packs','Suppliers','Users & roles','Alerts','Stages']){await page.locator('.settings-nav').getByRole('button',{name:n,exact:true}).click();await page.getByRole('heading',{name:n,exact:true}).waitFor();}
await page.getByRole('button',{name:'Add',exact:true}).click();await page.getByRole('textbox',{name:'Name',exact:true}).fill('Drying');await page.getByRole('textbox',{name:'Details',exact:true}).fill('Weight recording');await page.getByRole('button',{name:'Save changes'}).click();await page.getByRole('cell',{name:'Drying',exact:true}).waitFor();
await nav('Overview');await page.getByRole('heading',{name:'Know how production is doing.'}).waitFor();await nav('All screens');await page.getByRole('heading',{name:'One factory. Everything connected.'}).waitFor();
await nav('Production');await page.setViewportSize({width:390,height:844});await page.screenshot({path:'screen-processes-mobile.png',fullPage:true});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);console.log(JSON.stringify({checked:'12 process entry points; pressing and destinations; receiving and traceability; formulation batch creation; 5 reports; 7 configuration sections and editing; dashboard and screen catalogue',errors,mobileOverflow:overflow}));await browser.close();if(errors.length||overflow)process.exit(1)})().catch(e=>{console.error(e);process.exit(1)});
