'use client';
import {useState} from 'react';
import SystemScreens from './system-screens';
import {ArrowLeft, ArrowRight, Plus, Search, LayoutDashboard, Layers3, Package, Check, ChevronRight, Leaf, Scale, CircleHelp, X, CheckCircle2, Clock3, TrendingUp} from 'lucide-react';

type Stage = {name:string; input:number; outputs:{name:string;weight:number;kind:string}[]};
type Batch = {id:string;product:string;date:string;start:number;stages:Stage[];complete:boolean;units?:number;rejects?:number;pack?:number};
const initial:Batch[] = [
 {id:'CB-025',product:'Cocoa beans',date:'2026-09-14',start:100,complete:false,stages:[{name:'Roasting',input:100,outputs:[{name:'Roasted beans',weight:92.4,kind:'product'}]}]},
 {id:'CH-018',product:'70% Dark chocolate',date:'2026-09-14',start:100,complete:false,stages:[{name:'Chocolate making',input:100,outputs:[{name:'Chocolate',weight:97.4,kind:'product'},{name:'Waste',weight:0.6,kind:'waste'}]}]},
 {id:'CB-024',product:'Cocoa beans',date:'2026-09-13',start:80,complete:true,stages:[{name:'Roasting',input:80,outputs:[{name:'Roasted beans',weight:74,kind:'product'}]},{name:'Winnowing',input:74,outputs:[{name:'Nibs',weight:60,kind:'product'},{name:'Husks',weight:12,kind:'by-product'},{name:'Waste',weight:1,kind:'waste'}]}]},
];
const routes = ['Roasting','Winnowing','Grinding'];
const templates:Record<string,{name:string;kind:string}[]> = {'Roasting':[{name:'Roasted beans',kind:'product'},{name:'Unusable beans',kind:'waste'}],'Winnowing':[{name:'Nibs',kind:'product'},{name:'Whole peeled beans',kind:'product'},{name:'Husks',kind:'by-product'},{name:'Unusable beans',kind:'waste'}],'Grinding':[{name:'Liquor',kind:'product'},{name:'Waste',kind:'waste'}],'Moulding':[{name:'Finished chocolate',kind:'product'},{name:'Recoverable chocolate',kind:'rework'},{name:'Waste',kind:'waste'}]};
const kg=(n:number)=>n.toLocaleString('en',{minimumFractionDigits:2,maximumFractionDigits:2});
export default function Page(){
 const [batches,setBatches]=useState(initial); const [screen,setScreen]=useState('processes'); const [selected,setSelected]=useState('CB-025'); const [query,setQuery]=useState(''); const [filter,setFilter]=useState('All batches'); const [toast,setToast]=useState('');
 const [values,setValues]=useState<string[]>([]); const [extra,setExtra]=useState(false); const [error,setError]=useState(''); const [drafts,setDrafts]=useState<Record<string,string[]>>({});
 const batch=batches.find(b=>b.id===selected)!; const isChocolate=batch.product.includes('chocolate'); const next=isChocolate?(batch.stages.some(s=>s.name==='Moulding')?'':'Moulding'):routes[batch.stages.length];
 const input=batch.stages.length?batch.stages.at(-1)!.outputs[0].weight:batch.start;
 const rows=[...(templates[next]||[]),...(extra?[{name:'Other measured output',kind:'by-product'}]:[])];
 const total=values.reduce((a,v)=>a+(Number(v)||0),0); const useful=rows.reduce((a,r,i)=>a+(r.kind==='product'?(Number(values[i])||0):0),0);
 function go(s:string){setScreen(s);setError('');window.scrollTo(0,0)}
 function open(b:Batch){setSelected(b.id);go('detail')}
 function notify(s:string){setToast(s);setTimeout(()=>setToast(''),3500)}
 function update(b:Batch){setBatches(bs=>bs.map(x=>x.id===b.id?b:x))}
 function record(){setValues(drafts[batch.id]||[]);setExtra(false);go('stage')}
 const active=batches.filter(b=>!b.complete).length;
 return <div className="shell"><aside className="sidebar"><a className="logo" href="#" onClick={e=>{e.preventDefault();go('list')}}><span className="logo-icon"><Leaf size={24}/></span>cocoa<span className="logo-dot">.</span></a><div className="workspace">FACTORY WORKSPACE</div><nav>{[{name:'Overview',icon:LayoutDashboard,to:'dashboard'},{name:'Production',icon:Layers3,to:'processes'},{name:'Inventory',icon:Package,to:'inventory'},{name:'Formulations',icon:Scale,to:'formulations'},{name:'Reports',icon:TrendingUp,to:'reports'},{name:'Configuration',icon:Layers3,to:'configuration'},{name:'All screens',icon:LayoutDashboard,to:'catalog'}].map(n=><button key={n.to} className={(screen===n.to||(['list','detail','new','stage','pack','finish','operations','process','destinations','hold','correction','batch-report'].includes(screen)&&n.to==='processes'))?'nav active':'nav'} onClick={()=>go(n.to)}><n.icon size={19}/>{n.name}{n.to==='processes'&&<span className="nav-count">{active}</span>}</button>)}</nav><div className="side-bottom"><div className="help"><CircleHelp size={19}/><div>Made for the factory floor<small>Weigh. Record. Keep going.</small></div></div><div className="profile"><span className="avatar">AM</span><div>Alex Morgan<small>Production manager</small></div></div></div></aside>
 <div className="main"><header className="topbar"><div>Workspace <ChevronRight size={14}/><strong>{screen.replaceAll('-',' ').replace(/^./,c=>c.toUpperCase())}</strong></div><span className="demo"><span/> Interactive design preview</span></header><main>
 {['list','processes'].includes(screen)&&<div className="production-switch"><button className={screen==='processes'?'selected':''} onClick={()=>go('processes')}>Processes</button><button className={screen==='list'?'selected':''} onClick={()=>go('list')}>All batches <span className="count">{batches.length}</span></button></div>}
 {screen==='detail'&&<div className="batch-tools"><button className="secondary" onClick={()=>go('operations')}>More batch actions<ArrowRight size={16}/></button><button className="secondary" onClick={()=>go('batch-report')}>Batch report</button></div>}
 {screen==='new'&&<div className="info">Making chocolate? <button className="text-button" onClick={()=>go('formulations')}>Start from a formulation <ArrowRight size={14}/></button></div>}
 <SystemScreens screen={screen} go={go} batches={batches} selected={batch} open={open} create={b=>{setBatches([...batches,b]);setSelected(b.id);go('operations')}} update={update} notify={notify}/>
 {screen==='list'&&<><div className="heading"><div className="eyebrow">PRODUCTION</div><div className="title-row"><div><h1>A good day to make chocolate.</h1><p>Every batch, from the first weigh-in to the final bar.</p></div><button className="primary" onClick={()=>go('new')}><Plus size={18}/>New batch</button></div></div><div className="stats"><Stat label="Batches in progress" value={String(active)} foot="On the factory floor" icon={<Layers3/>}/><Stat label="Material started" value={`${kg(batches.reduce((a,b)=>a+b.start,0))} kg`} foot="Across these sample batches" icon={<Scale/>}/><Stat label="Completed batches" value={String(batches.length-active)} foot="Production recorded" icon={<CheckCircle2/>}/></div><section className="panel"><div className="panel-head"><div><h2>Your batches <span className="count">{batches.length}</span></h2><p>A clear next step for every batch.</p></div><label className="search"><Search size={17}/><input placeholder="Search batches…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="tabs">{['All batches','In progress','Completed'].map(f=><button key={f} className={filter===f?'selected':''} onClick={()=>setFilter(f)}>{f}</button>)}</div><div className="table-wrap"><table><thead><tr><th>BATCH / PRODUCT</th><th>STARTED</th><th>INPUT</th><th>CURRENT STAGE</th><th>STATUS</th><th/></tr></thead><tbody>{batches.filter(b=>(filter==='All batches'||(filter==='Completed'?b.complete:!b.complete))&&`${b.id} ${b.product}`.toLowerCase().includes(query.toLowerCase())).map(b=><tr key={b.id}><td><button className="batch-link" onClick={()=>open(b)}>{b.id}</button><small>{b.product}</small></td><td>{b.date.slice(8)} Sep 2026</td><td>{kg(b.start)} <span className="muted">kg</span></td><td>{b.complete?'Finished':b.stages.at(-1)?.name||'Ready to start'}</td><td><span className={'badge '+(b.complete?'done':'progress')}>{b.complete?<Check size={12}/>:<span className="dot"/>}{b.complete?'Completed':'In progress'}</span></td><td><button className="round" aria-label={`Open ${b.id}`} onClick={()=>open(b)}><ArrowRight size={18}/></button></td></tr>)}</tbody></table></div></section><div className="quiet-note"><Leaf size={16}/>Good records start with a simple measurement. We take care of the maths.</div></>}
 {screen==='new'&&<><Back onClick={()=>go('list')} label="All batches"/><div className="form-heading"><div className="eyebrow">LET’S GET STARTED</div><h1>Start a new batch</h1><p>Just the basics. You’ll record outputs as production moves along.</p></div><form className="panel form-panel" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);const id=String(d.get('id')).trim();if(batches.some(b=>b.id===id)){setError('That batch number already exists. Use another number.');return} const b:Batch={id,product:String(d.get('product')),date:String(d.get('date')),start:Number(d.get('weight')),complete:false,stages:[]};setBatches([...batches,b]);setSelected(id);go('detail');notify('Batch created. Ready for your first stage.')}}><h2>Batch details</h2><div className="form-grid"><label>Batch number<input name="id" defaultValue={`CB-0${26+batches.length-3}`} required/></label><label>Production date<input name="date" type="date" defaultValue="2026-09-14" required/></label></div><label>Starting material<select name="product"><option>Cocoa beans</option></select></label><label>Starting weight<div className="unit-input"><input name="weight" type="number" min="0.01" step="0.01" placeholder="0.00" required/><span>kg</span></div><small>Enter the weight you measured before production.</small></label><div className="info">This preview follows cocoa beans through roasting, winnowing, and grinding. Open CH-018 to try chocolate moulding and packaging.</div>{error&&<div role="alert" className="error">{error}</div>}<div className="form-actions"><button type="button" className="secondary" onClick={()=>go('list')}>Cancel</button><button className="primary">Create batch<ArrowRight size={17}/></button></div></form></>}
 {screen==='detail'&&<><Back onClick={()=>go('list')} label="All batches"/><div className="title-row detail-title"><div><div className="eyebrow">BATCH {batch.id}</div><h1>{batch.product}</h1><p>Started {batch.date} <span className="separator">·</span> {kg(batch.start)} kg starting weight</p></div><span className={'badge '+(batch.complete?'done':'progress')}>{batch.complete?'Completed':'In progress'}</span></div><div className="detail-grid"><section className="panel journey"><div className="panel-head"><div><h2>Batch journey</h2><p>Your measurements, one stage at a time.</p></div></div>{batch.stages.map((s,i)=><div className="stage-record" key={i}><span className="step checked"><Check size={16}/></span><div className="stage-content"><div className="stage-title"><h3>{s.name}</h3><span className="muted">Recorded</span></div><div className="output-tags">{s.outputs.filter(o=>o.weight>0).map((o,j)=><span key={j}>{o.name}<strong>{kg(o.weight)} kg</strong></span>)}</div><details><summary>View measurement details</summary><p>Input: {kg(s.input)} kg · All measured outputs: {kg(s.outputs.reduce((a,o)=>a+o.weight,0))} kg</p><p>Unaccounted variance: {kg(s.input-s.outputs.reduce((a,o)=>a+o.weight,0))} kg</p></details></div></div>)}{batch.units!==undefined&&<div className="stage-record"><span className="step checked"><Check size={16}/></span><div><h3>Packaging</h3><p>{batch.units-batch.rejects!} accepted bars · {batch.rejects} rejected · {batch.pack}g each</p></div></div>}{!batch.complete&&<div className="stage-record next-stage"><span className="step">{batch.stages.length+1}</span><div><div className="eyebrow">UP NEXT</div><h3>{next|| (isChocolate&&batch.units===undefined?'Packaging':'Complete batch')}</h3><p>{next?'Weigh your outputs, then enter them here.':'Review the finished quantities and close this batch.'}</p><button className="primary" onClick={()=>{if(next)record();else go(isChocolate&&batch.units===undefined?'pack':'finish')}}>{next?`Record ${next.toLowerCase()}`:isChocolate&&batch.units===undefined?'Record packaging':'Review & complete'}<ArrowRight size={17}/></button></div></div>}</section><aside><div className="panel summary-card"><span className="eyebrow">MATERIAL AVAILABLE</span><div className="big-number">{kg(input)}<span> kg</span></div><p>{batch.stages.at(-1)?.outputs[0].name||batch.product}</p><hr/><div className="mini-row"><span>Source batch</span><strong>{batch.id}</strong></div><div className="mini-row"><span>Stages recorded</span><strong>{batch.stages.length}</strong></div></div><div className="tip"><Scale size={21}/><h3>Only enter what you weigh.</h3><p>Yield, waste and unexplained differences are calculated for you.</p></div></aside></div></>}
 {screen==='stage'&&<><Back onClick={()=>go('detail')} label={`Batch ${batch.id}`}/><div className="form-heading"><div className="eyebrow">{batch.id} <span className="separator">/</span> RECORD A STAGE</div><h1>{next}</h1><p>Enter each measured output. We’ll work out the balance.</p></div><div className="entry-layout"><form className="panel form-panel" onSubmit={e=>{e.preventDefault();if(!values[0]||Number(values[0])<=0){setError('Enter a measured weight for the main output.');return}if(total>input){setError('Outputs exceed the input. Check your weights before saving.');return}update({...batch,stages:[...batch.stages,{name:next,input,outputs:rows.map((r,i)=>({...r,weight:Number(values[i])||0}))}]});go('detail');notify(`${next} saved. Your batch is up to date.`)}}><div className="input-banner"><span>Input · {batch.stages.at(-1)?.outputs[0].name||batch.product}</span><strong>{kg(input)} kg</strong></div><h2>What came out?</h2><p className="form-subtitle">Weigh separately. Leave unused categories blank.</p>{rows.map((r,i)=><label key={r.name} className="weight-row"><span>{r.name}<small>{r.kind==='product'?'Useful product':r.kind==='by-product'?'By-product':r.kind==='rework'?'Recoverable material':'Recorded waste'}</small></span><div className="unit-input"><input aria-label={r.name} type="number" step="0.01" min="0" placeholder="0.00" value={values[i]||''} onChange={e=>setValues(v=>{const a=[...v];a[i]=e.target.value;return a})}/><span>kg</span></div></label>)}{!extra&&<button type="button" className="text-button" onClick={()=>setExtra(true)}><Plus size={15}/>Add another output</button>}{error&&<div className="error" role="alert">{error}</div>}<div className="form-actions"><button type="button" className="secondary" onClick={()=>{setDrafts({...drafts,[batch.id]:values});go('detail');notify('Draft saved for this session.')}}>Save draft</button><button className="primary">Save stage<Check size={17}/></button></div></form><aside><div className="panel balance"><div className="eyebrow">LIVE BALANCE</div><h2>Everything adds up here.</h2><div className="mini-row"><span>Input weight</span><strong>{kg(input)} kg</strong></div><div className="mini-row"><span>Measured outputs</span><strong>{kg(total)} kg</strong></div><hr/><span className="muted">Unaccounted variance</span><div className="big-number">{kg(input-total)}<span> kg</span></div><div className="meter"><span style={{width:`${Math.min(100,total/input*100)}%`}}/></div><p>{(total/input*100).toFixed(1)}% of input accounted for</p><div className="mini-row"><span>Useful product yield</span><strong>{(useful/input*100).toFixed(1)}%</strong></div></div><div className="tip"><CircleHelp size={20}/><p>A difference isn’t automatically waste. It may include moisture loss or material left in equipment.</p></div></aside></div></>}
 {screen==='pack'&&<><Back onClick={()=>go('detail')} label={`Batch ${batch.id}`}/><div className="form-heading"><div className="eyebrow">FINISHING TOUCHES</div><h1>Record packaging</h1><p>Count the bars. Include rejects in the total made.</p></div><form className="panel form-panel" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);const units=Number(d.get('units')),rejects=Number(d.get('rejects')),pack=Number(d.get('pack'));if(rejects>units){setError('Rejected units cannot exceed total units.');return}update({...batch,units,rejects,pack});go('detail');notify('Packaging saved.')}}><h2>{batch.product}</h2><label>Pack size<select name="pack"><option value="45">45g bar</option><option value="100">100g bar</option></select></label><div className="form-grid"><label>Total units made<input name="units" type="number" min="1" step="1" required placeholder="e.g. 1896"/></label><label>Rejected units<input name="rejects" type="number" min="0" step="1" required defaultValue="0"/></label></div><div className="info">Accepted units = total made − rejected units. Pack-size weights are nominal, not measured.</div>{error&&<div className="error" role="alert">{error}</div>}<div className="form-actions"><button type="button" className="secondary" onClick={()=>go('detail')}>Cancel</button><button className="primary">Save packaging<Check size={17}/></button></div></form></>}
 {screen==='finish'&&<><Back onClick={()=>go('detail')} label={`Batch ${batch.id}`}/><div className="form-heading"><div className="eyebrow">{batch.id}</div><h1>Ready to finish?</h1><p>One last look at what this batch produced.</p></div><div className="panel form-panel"><div className="completion-icon"><CheckCircle2 size={30}/></div><h2>{batch.product}</h2><div className="mini-row"><span>Starting material</span><strong>{kg(batch.start)} kg</strong></div><div className="mini-row"><span>Final measured product</span><strong>{kg(input)} kg</strong></div>{batch.units!==undefined&&<><div className="mini-row"><span>Accepted bars</span><strong>{batch.units-batch.rejects!}</strong></div><div className="mini-row"><span>Nominal accepted weight</span><strong>{kg((batch.units-batch.rejects!)*batch.pack!/1000)} kg</strong></div></>}<div className="info">Design preview: closing updates this session only. Inventory destinations and final material reconciliation will be added to the working system.</div><div className="form-actions"><button className="secondary" onClick={()=>go('detail')}>Back to batch</button><button className="primary" onClick={()=>{update({...batch,complete:true});go('detail');notify('Batch completed.')}}>Complete batch<Check size={17}/></button></div></div></>}
 {screen==='overview'&&<><div className="eyebrow">FACTORY OVERVIEW</div><h1>A little clarity, every day.</h1><p>Production at a glance · sample data</p><div className="stats"><Stat label="In progress" value={String(active)} foot="Batches on the floor" icon={<Clock3/>}/><Stat label="Completed" value={String(batches.length-active)} foot="Batches recorded" icon={<CheckCircle2/>}/><Stat label="Recorded stages" value={String(batches.reduce((a,b)=>a+b.stages.length,0))} foot="Measurements captured" icon={<TrendingUp/>}/></div><div className="panel overview-panel"><h2>Keep production moving</h2>{batches.filter(b=>!b.complete).map(b=><button className="overview-row" onClick={()=>open(b)} key={b.id}><span><strong>{b.id}</strong><small>{b.product}</small></span><span>Continue batch <ArrowRight size={17}/></span></button>)}</div></>}
 {screen==='materials'&&<><div className="eyebrow">MATERIALS</div><h1>See what came out.</h1><p>Recorded outputs and their source batches. This preview is not a stock ledger.</p><div className="panel table-wrap"><table><thead><tr><th>MATERIAL</th><th>CLASSIFICATION</th><th>RECORDED OUTPUT</th><th>SOURCE</th></tr></thead><tbody>{batches.flatMap(b=>b.stages.flatMap(s=>s.outputs.filter(o=>o.weight>0).map((o,i)=><tr key={`${b.id}-${s.name}-${i}`}><td>{o.name}</td><td>{o.kind}</td><td>{kg(o.weight)} kg</td><td><button className="batch-link" onClick={()=>open(b)}>{b.id}<ArrowRight size={14}/></button></td></tr>)))}</tbody></table></div></>}
 </main><footer><span>COCOA PRODUCTION</span><span>Screen prototype · Sample data · Changes reset on refresh</span></footer></div>{toast&&<div className="toast" role="status"><CheckCircle2 size={18}/>{toast}<button aria-label="Dismiss notification" onClick={()=>setToast('')}><X size={15}/></button></div>}</div>
}
function Back({onClick,label}:{onClick:()=>void;label:string}){return <button className="back" onClick={onClick}><ArrowLeft size={15}/>{label}</button>}
function Stat({label,value,foot,icon}:{label:string;value:string;foot:string;icon:React.ReactNode}){return <div className="panel stat"><div className="stat-top">{label}<span>{icon}</span></div><div className="stat-value">{value}</div><small>{foot}</small></div>}
